markdown: kramdown
highlighter: rouge
paginate: 10
language: 'en-uk'
url: "https://blog.convictional.com"
baseurl: /
title: Convictional Blog
description: Convictional is the easiest way for suppliers to accept & automate B2B orders from any trading partners. Our blog covers B2B, EDI, integration, drop shipping and more for suppliers and wholesalers.
cover: assets/images/melanie-magdalena-340093-unsplash.jpg
logo: assets/images/logo-small.png
logo_dark: assets/images/logo-small.png
favicon: assets/images/logo-small.png
production_url: https://blog.convictional.com
source_url: https://blog.convictional.com
navigation: True
subscribers: True
google_analytics: UA-109651638-1 # replace with your GA tracking identifier
permalink: /:title
plugins: [jekyll-paginate, jekyll-feed, jekyll-sitemap]
feed:
  path: feed.xml
  url: https://blog.convictional.com
safe: False
lsi: False
username: convictional
repo: convictional-blog
branch: master
relative_source: _site/
destination: _site/
production_url: https://blog.convictional.com
source_url: https://blog.convictional.com
exclude:
  - assets/css
  - node_modules
  - vendor
  - .travis.yml
  - Gemfile
  - Gemfile.lock
  - GHOST.txt
  - gulpfile.js
  - LICENSE
  - package.json
  - Rakefile
  - README.md
  - script.py
  - changelog.md
  - "*.Rmd"
  - .git*
