markdown: kramdown
highlighter: rouge
paginate: 10
language: 'en-us'
url: "https://blog.convictional.com"
baseurl: https://blog.convictional.com/
title: Convictional Blog
description: Convictional - The First B2B Trade Enablement Network
cover: assets/images/hero.png
logo: assets/img/logo.png
logo_dark: assets/img/logo.png
favicon: assets/img/logo.png
production_url: https://blog.convictional.com
source_url: https://blog.convictional.com
navigation: True
subscribers: True
google_analytics: UA-109651638-6
permalink: /:title
plugins: [jekyll-paginate, jekyll-feed, jekyll-sitemap]
feed:
  path: feed.xml
  url: https://blog.convictional.com
safe: False
lsi: False
username: convictional
repo: convictional-blog
branch: master
relative_source: _site/
destination: _site/
production_url: https://blog.convictional.com
source_url: https://blog.convictional.com
exclude:
  - assets/css
  - node_modules
  - vendor
  - .travis.yml
  - Gemfile
  - Gemfile.lock
  - GHOST.txt
  - gulpfile.js
  - LICENSE
  - package.json
  - Rakefile
  - README.md
  - script.py
  - changelog.md
  - "*.Rmd"
  - .git*
