backend:
  name: github
  branch: master
publish_mode: editorial_workflow
media_folder: "assets/images"
collections:
  - name: "post"
    label: "Posts"
    folder: "_posts/"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "Layout", name: "layout", widget: "hidden", default: "post"}
      - {label: "Current", name: "current", widget: "hidden", default: "post"}
      - {label: "Cover", name: "cover", widget: "image"}
      - {label: "Navigation", name: "navigation", widget: "hidden", default: "True"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Date", name: "date", widget: "datetime"}
      - {label: "Tags", name: "tags", widget: }
      - {label: "Class", name: "class", widget: "hidden", default: "post-template"}
      - {label: "Author", name: "author", widget: "string"}